### ISSUE TITLE
Prerequisites: Give more instructions on how/where to place geckodriver executable in system path

### ISSUE THREAD

**Issue by MarckK** [hjwp/Book-TDD-Web-Dev-Python#105]
There is some question of how to do this in the comments section with a few people unsure of what steps are necessary. One user suggested installing Homebrew and running "brew install geckodriver".

It's useful to know how to place an executable in _/usr/local/bin_ oneself and straightforward to do. Would you like me to make a PR with instructions?

**Comment by hjwp** [comment]
closing this because geckodriver is now bundled with firefox
