### ISSUE TITLE
Add next chapter link in chapter_unit_test_first_view 

### ISSUE THREAD

**Issue by syyong** [hjwp/Book-TDD-Web-Dev-Python#108]
I would like to add next chapter link at the bottom of this page https://www.obeythetestinggoat.com/book/chapter_unit_test_first_view.html
to make it easier to get to the next page as suggested by the other user. Is it ok that I go ahead?

**Comment by hjwp** [comment]
I'm guessing you've thoroughly moved on, but in case anyone else wants to mess with the html generation, you're certainly welcome to do so!  maybe take a look at `copy-html-to-site-and-print-toc.py`. closing for now.
