### ISSUE TITLE
asciidoctor: ERROR: book.asciidoc

### ISSUE THREAD

**Issue by wangzhaohe** [hjwp/Book-TDD-Web-Dev-Python#110]
When make book.html, Error displayed:

asciidoctor: ERROR: book.asciidoc: line 18: include file not found: /Users/swot/offline/Book-TDD-Web-Dev-Python/part1.harry.asciidoc
asciidoctor: ERROR: book.asciidoc: line 30: include file not found: /Users/swot/offline/Book-TDD-Web-Dev-Python/part2.harry.asciidoc
asciidoctor: ERROR: book.asciidoc: line 42: include file not found: /Users/swot/offline/Book-TDD-Web-Dev-Python/part3.harry.asciidoc

**Comment by hjwp** [comment]
should be fixed now.  thanks!
