### ISSUE TITLE
Wrong class in code snippet in chapter 23

### ISSUE THREAD

**Issue by moritz-weber** [hjwp/Book-TDD-Web-Dev-Python#111]
In _Chapter 23: Test Isolation, and “Listening to Your Tests”_ in the first code snippter after _Moving Down to the Forms Layer_ it says:

    class NewListForm(models.Form):

Which was irritating, as there is no `models.Form` (PyCharm was complaining). It wasn't a big issue, as it is corrected a few pages later, but it took me a few minutes because I thought I missed something.

**Comment by hjwp** [comment]
it's been a while i know but i've fixed it i think.  thanks!
