### ISSUE TITLE
ch17|023 - Replace import to enable easier migration to Django 2

### ISSUE THREAD

**Issue by HelloThisIsFlo** [hjwp/Book-TDD-Web-Dev-Python#117]
Instead of importing
```python
from django.core.urlresolvers import reverse
```
we could import 
```python
from django.urls import reverse
```

Importing from `urlresolvers` is only kept for backwards compatibility, and it isn't working
in Django 2.0 anymore.  
See: https://docs.djangoproject.com/en/1.11/ref/urlresolvers/

**Comment by hjwp** [comment]
thanks!  working on the django 4 version now :)
