### ISSUE TITLE
Realy stuck on unix socket

### ISSUE THREAD

**Issue by Malomalsky** [hjwp/Book-TDD-Web-Dev-Python#126]
I am stucked on chapter with sockets. 
I did everything according to the guide: 

_/etc/nginx/sites-avalible/malomalsky.studio_

```
server {
listen 80;
server_name malomalsky.studio;

location /static/ {
    alias /home/malomalsky/sites/malomalsky.studio/static;
    }

location / {
    proxy_pass http://unix:/tmp/malomalsky.studio.socket;
    }
}

```
`../virtualenv/bin/gunicorn  --bind unix:/tmp/malomalsky.studio.socket superlists.wsgi:application`

Gunicorn works without any errors, but i have 502 Bad request error. 

Ubunty 18

**Comment by hjwp** [comment]
am assuming you figured something out?  well done if so!  good luck with the rest of the book.  once you're through the deploy chapters things get a little less tricky...
