### ISSUE TITLE
Quotation marks needed for "$ python -c from selenium..."?

### ISSUE THREAD

**Issue by prcantwell** [hjwp/Book-TDD-Web-Dev-Python#188]
In the [online version of the book](https://www.obeythetestinggoat.com/) (Third Edition Early Release), in the section on [Installing Django and Selenium](https://www.obeythetestinggoat.com/book/pre-requisite-installations.html#_installing_django_and_selenium), I think that quotation marks might be needed around the Python command when invoking the interpreter with `-c`.

Currently, the book suggests this command:

```
(.venv) $ python -c from selenium import webdriver; webdriver.Firefox()
```

I had to add quotation marks to make it run:

```
(.venv) $ python -c "from selenium import webdriver; webdriver.Firefox()"
```

I tried on Windows 10 (Git Bash and PowerShell), Linux (bash), and Mac (zsh).  Quotation marks were needed in each case.

I don't know if quotation marks are strictly necessary in all cases though, as the [docs](https://docs.python.org/3/tutorial/interpreter.html#invoking-the-interpreter) only say that "it is usually advised to quote _command_ in its entirety".

I'm looking forward to the Third Edition!  It's great to have access to the early release as it becomes available.

**Comment by hjwp** [comment]
fixed!   thank you very much Patrick :)
