### ISSUE TITLE
early release book ~issue / geckodriver.log

### ISSUE THREAD

**Issue by devinschumacher** [hjwp/Book-TDD-Web-Dev-Python#193]
Hello, I'm reading early release book and there was something I encounter that's not really your fault but I think it's probably worth mentioning because it took me a couple hours to figure out how to do bug and it could save some people a lot of time.

Early in the book, you show a screenshot of how are your project folder should look and there's a file geckodriver.log in it.

I couldn't figure out how to get this to generate for the life of me until I found one of my other projects that did have it. so i deleted the file, ran it and got a log!

Anyways, it turns out after downgrading selenium the log file generated again so something in their new updates. I guess does not automatically generate logs which might be confusing to some users!

certainly was for me.

cheers

**Comment by hjwp** [comment]
Thanks so much Devin!  I just tried it myself, and sure enough, it looks like selenium v 4.14 does not produce *geckodriver.log* by default any more.  I had v 4.9.1.  upgrading now!

**Comment by hjwp** [comment]
https://github.com/hjwp/Book-TDD-Web-Dev-Python/commit/e7a38cdb6ea8ed6a48f3ed63c42352391584a945  ;-)
