### ISSUE TITLE
Python version mismatch

### ISSUE THREAD

**Issue by RivenSkaye** [hjwp/Book-TDD-Web-Dev-Python#221]
There's a mismatch between the prerequisite and preface version listings.
[pre-requisite-installations](https://github.com/hjwp/Book-TDD-Web-Dev-Python/blob/508759e8c26deacca9b0c5ab87c8f6a22b503262/pre-requisite-installations.asciidoc?plain=1#L29) says it was tested on Python 3.12 and might require editing or produce different messages and error logs for other Python versions, whereas [the preface](https://github.com/hjwp/Book-TDD-Web-Dev-Python/blob/508759e8c26deacca9b0c5ab87c8f6a22b503262/preface.asciidoc?plain=1#L48) notes the book was updated for use with Python 3.11.

The image embedded on the pre-requisite-installations page shows the 3.11 installer as well.

**Comment by hjwp** [comment]
thanks for this!  I'll update the preface and make a note to take a new screenshot.  Carry on with 3.12 if you aren't already!
