### ISSUE TITLE
Chapter 16: Persona login fails at the last hurdle.

### ISSUE THREAD

**Issue by Charlotteis** [hjwp/Book-TDD-Web-Dev-Python#25]
Hi Harry. Firstly, thanks for writing this book, I am learning a lot.

I went through the Spike for implementing a Persona Login and encountered an error, then went through and did the "real" (test-driven) implentation and encountered the same error.

`MultiValueDictKeyError at /accounts/login`
`""assertion'"`

It has something to do with the following code:
`    user = authenticate(assertion=request.POST["assertion"]) `
Unfortunately I don't know why this is happening.

When I run the functional tests, I get 
`selenium.common.exceptions.TimeoutException: Message: ''`

**Comment by hjwp** [comment]
Hi there, glad you're finding the book useful!

This error looks weird -- it has a mixture of double and single quotes in.  Could that be a clue pointing to a possible typo?  Either in your code in authenticate.py or maybe in the client-side javascript maybe?
```
MultiValueDictKeyError at /accounts/login
""assertion'"

```
Drop me an email to obeythetestinggoat@gmail.com and we'll try and figure it out...
