### ISSUE TITLE
Grammatical Error Chapter 11 

### ISSUE THREAD

**Issue by mshob23** [hjwp/Book-TDD-Web-Dev-Python#252]
![image](https://github.com/hjwp/Book-TDD-Web-Dev-Python/assets/35338570/38452437-c5a4-443f-ba61-3e8573fd80d9)
I believe here you either mean to say "one of my old employers, PythonAnywhere" or "my old employer, PythonAnywhere"

**Comment by hjwp** [comment]
thanks very much for the suggestion!  much appreciated.


i think this one is more of a cultural / personal preference, whether you refer to an "employer" as a single thing, or you refere to them in the plural - them / employers.  companies are made up of many people...  it's quite common in the uk.
