### ISSUE TITLE
Issues found on chapters 9 and 10

### ISSUE THREAD

**Issue by artGonza** [hjwp/Book-TDD-Web-Dev-Python#281]
First I want to start by saying the following:
I followed the previous version of this tutorial a few year back, and I have returned to learn about docker and a few other things I had issues with.
So I did not follow from the beginning, instead I tried a couple of different ways of starting from chapter 8.

I found the following: 

Issues 1 and 2 might be because I did not follow the tutorial from the beginning. 
1. 9.11 Running code "inside" the container with docker exec
    while in bash, I was not sure how to exit, tried control C and later exit, maybe mention that in the tutorial?

      </html>
      * Connection #0 to host localhost left intact
      
      root@942b063540c6:/src# ^C

      root@942b063540c6:/src# ^C

      root@942b063540c6:/src# exit

      exit
2. 9.11
    section: Docker Port Mapping
    Instead of the error ==>  curl: (52).... ==> reported in the tutorial, I get:
        > User-Agent: curl/8.6.0
        > Accept: */*
        >
        * Recv failure: Connection reset by peer
        * Closing connection
        curl: (56) Recv failure: Connection reset by peer
3. 9.12 Database migrations
    Not sure you meant to show this subtitle:
      Should we run "migrate" inside the Dockerfile? No. // JAN: Not sure I understand this line. 
      You’re saying that we shouldn’t run migrate inside our Dockerfile, but then in the next line you 
      do exactly that
4. 9.13 Mounting files inside the container
      the db.sqlite3 file is added to .gitignore
      So I think the commit flag at the end of the chapter should be -am instead of -m otherwise 
      .gitignore is not included in the commit.
5. When running the tests in chapter 9, three different test commands are used
    TEST_SERVER=localhost:8888 ./src/manage.py test src/functional_tests --failfast
    TEST_SERVER=localhost:8888 ./manage.py test functional_tests --failfast
    TEST_SERVER=localhost:8888 ./src/manage.py test src/functional_tests --failfast
    Then in chapter 10 it changes to:
    TEST_SERVER=localhost:8888 python src/manage.py test functional_tests --failfast
    Is that intentional, like to show different ways to run the tests?

Issues 6 and 9 again might be related to the way I started in the middle of the tutorial.
6. 10.3 Serving Static Files with Whitenoise

    Text says:
        And if you take another manual look at your site after rebuilding the container, things should 
        look much healthier
    Docker did not install whitenoise in my system, I had to install it manually.
7. 10.4 Using requirements.txt
    After adding the libraries to the requirements.txt file when committing, the tutorial text shows 
    (*)'s for the commit:

        $ *git add requirements.txt*
        $ *git commit -m "Add a requirements.txt with Django, gunicorn and whitenoise"*
9. 10.4 Using requirements.txt
    The tutorial text show the Dockerfile at the end as 
        WORKDIR /src 
        CMD python manage.py runserver
    
    I think the last line should read
        CMD gunicorn --bind :8888 superlists.wsgi:application
10. 10.5 Using Environment Variables to Adjust Settings for Production
    I stoped here, not sure how to proceed. 
        Section: Collectstatic is Required when Debug is Turned Off
              Tutorial text says:
                Let’s quickly adjust our gitignore, since the static folder is in a new place
                
                collectstatic in the dockerfile does not generate a static folder in the project,
                there is no static folder inside the src folder
        
                If I try to manually run collectstatic,
                % python ./src/manage.py collectstatic
                when i rerun the docker file I get:
                --------------------
                  10 |     WORKDIR /src
                  11 |
                  12 | >>> RUN python manage.py collectstatic
                  13 |
                  14 |     ENV DJANGO_DEBUG_FALSE=1
                --------------------
                ERROR: failed to solve: process "/bin/sh -c python manage.py collectstatic" did not 
                complete successfully: exit code:
11. 10.6 Switching to a nonroot user
    Is this section supposed to show on the tutorial yet? Not sure what to do here

I loved the previous version of the tutorial I learn a lot. I hope mentioning all of this does not come out wrong, sorry for the wall of text, really appreciate all I learned.

To start the project from chapter 8 I did:

    create directory
    cd to that directory
    git init
    git pull https://github.com/hjwp/book-example.git chapter_08_prettification
    I read somewhere you are supposed to remove the old migration files, so i did and then:
    run makemigrations and migrate
    run collectstatic
    git commit

Was that a good way to start from chapter 8?

Thank you for your time
Kind regards 
ArtGonza

**Comment by hjwp** [comment]
thank you *so* much for these comments and suggestions ArtGonza, they are _really_ helpful, i really appreciate you taking the time to write them, and your attention to detail!  will get on and make some updates to those chapters asap.

**Comment by hjwp** [comment]
i think i've managed to address all of these!  thanks again for all your suggestions, and let me know if you ever have a try at chapter 11?

https://github.com/hjwp/Book-TDD-Web-Dev-Python/commit/57ef5677faf5126869f6e091c3a74ae7a2e17d34
