### ISSUE TITLE
Erratas found chapters 15 to 18

### ISSUE THREAD

**Issue by artGonza** [hjwp/Book-TDD-Web-Dev-Python#314]
1) 15.4, I think you are missing a word: 'see'
    Right after the code block: 
    src/lists/templates/base.html (ch15l019)
    web tutorial says:
    1
    2
    3
    4 If you just try to use form.errors.text you’ll (word missing here) that Django...

2)  15.4 A Little Digression on Queryset Ordering and String Representations
    The word 'would'
    in the parenthesis, the web tutorial says:
    (what else ==> wouold <== it sort by after all?)

3) 16.4, Not sure if it was done on purpose, just a small suggestion: 
    src/lists/static/tests/Spec.js (ch16l010)
    The last line, the code block ends with: [...]
    That's confusing, the smoke test was removed, that's all the code that file has
    at that moment, maybe end it with: 
        });

4) 16.5, At the end of the chapter code block: src/lists/static/lists.js (ch16l014)
    The last line, I think is missing a ';'
    Because later in 16.6 that same line has the semicolon at code block: 
    src/lists/static/lists.js (ch16l016)
    
5) 16.6, the image at 'Figure 5. Jasmine tests with console.log debug outputs'
    In the previous chapter after the missing semi-colon,
    the tutorial says 'That doesn’t work! We get an unexpected error:'
    ==>[...]
    ==>Error during loading: TypeError: textInput is null in ...
    However after making changes to the code, on the figure in this chapter the 
    Jasmine report says:
    ==>Error during loading: Script error. in file ...
    Just letting you know I am still getting the same error since only some 
    console.logs were added.
    ==>Error during loading: TypeError: textInput is null in ...

6) 16.9 missing ';' on block code: 
    src/lists/static/tests/Spec.js (ch16l022)
    Don't know anything about JS, but are theses lines missing their ';' ?
    ==> 4th line from the top: const inputSelector = `#${inputId}` 
    ==> 4th line from the bottom: document.body.appendChild(testDiv) 
    ==> 5th line from bottom: Should there be a ';' at the end of the backtick? 
    
    It was not specified, but it looks like you are removing the the console.logs
    this one still has it, function: 
    beforeEach(()
    console.log("beforeEach");

7) 16.10 Add a space? between -m and "
    git commit -m"Despike our js, add jasmine tests"

8) Chapter 16.11 and 16.12 have a class="tok-err" showing  red squares
    src/lists/static/tests/Spec.js (ch16l032)
    src/lists/templates/base.html (ch16l034)
![Screenshot 2024-08-31 at 6 46 51 PM](https://github.com/user-attachments/assets/8e8bd484-230c-4695-addf-416370f7e4a1)

![Screenshot 2024-08-31 at 6 52 15 PM](https://github.com/user-attachments/assets/41b7e04f-419b-4035-b41b-36dd316b4d15)

9) 18.2 "Sending Emails from Django"
    This creates a little confusion:
    ==> cd src && python manage.py startapp accounts 
    Later in subchapter: "Finishing the Custom Django Auth"
    ==> $ git checkout main # switch back to main branch
    The next two lines, either be inside src directory or outside
    ==> $ rm -rf accounts # remove any trace of spiked code
    ==> $ git add src/functional_tests/test_login.py
    ==> $ git commit -m "FT for login via email"
    Same thing happens in chapter 18.4 "A Minimal Custom User Model"
    ==> $ rm src/accounts/tests.py
    Gives error: rm: src/accounts/tests.py: No such file or directory
    Gotta cd out first. Or maybe that's the intention, to keep the student alert...

10) 18.2 "Custom Authentication Models" code block: 
    src/accounts/models.py (ch18l010)
    this line:
    [...]
    suggests to me this block of code goes at the end, but that causes an error,
    I think  
    class ListUserManager 
    should appear before 
    class ListUser

11) 18.2 "Finishing the Custom Django Auth" code block:
    src/accounts/authentication.py (ch18l012)
    ==> class PasswordlessAuthenticationBackend
        ==> [...]
        ==> except ListUser.DoesNotExist 
    getting a warning on that exception, I think is related to class ListUser

12) 18.2 I was getting error:
    "SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed..."
    Not sure you want to mention this or not. 
    I am on a mac, turns out I needed to run the:
    Install Certificates.command
    Located at Applications/Python 3.myVersion/
    https://stackoverflow.com/questions/59411362/ssl-certificate-verify-failed-certificate-verify-failed-unable-to-get-local-i

13) Chapter 18.4 After the changes made to the model
    src/accounts/models.py (ch18l030)
    Tutorial text says:
    And now we get a different error again, slightly more familiar this time! Django 
    is a bit happier with the structure of our custom User
    model, but it’s unhappy about the database:
        django.db.utils.OperationalError: no such table: accounts_user
    
    I think it's necessary to mention that this error happens when running the test,
    because up until this point we have been running:
        $ python src/manage.py makemigrations
    So that's what I did, and I did not get that last error message, I had to erase 
    my migration, then run the test in order to get that error

14) 18.5 A Token Model to Link Emails with a Unique ID
    I think there is an error here, tutorial text says:
    I’ll trust you to go through these conscientiously—remember, r: Token() got unexpected keyword arguments: email I may not be able to
        see you, but the Testing Goat can!
    
    I think this got pasted somehow:
        r: Token() got unexpected keyword arguments: email

Learning a lot, thanks
Cheers
ArtGonza

**Comment by hjwp** [comment]
Thanks so much for these @artGonza !  I've tried to address all of them in https://github.com/hjwp/Book-TDD-Web-Dev-Python/pull/317

a couple of things i thought i'd respond to:

* re: `space? between -m and "` in git commits, that's not necessary, and by force of habit i don't do them.
* I couldn't repro the `SSL: CERTIFICATE_VERIFY_FAILED` problem, will ask a couple of other people to take a look

Thanks _so_ much, I really appreciate your attention to detail!   I'm sorry that you're now into the slightly rougher chapters of the book that haven't been through tech review, but do let me know how you like them!  eg the next chapter on nocking?
