### ISSUE TITLE
Small grammatical error 

### ISSUE THREAD

**Issue by mshob23** [hjwp/Book-TDD-Web-Dev-Python#321]
![Chapter13_mistake2](https://github.com/user-attachments/assets/9409b0f9-e71f-4b10-a040-3d4f06c74ded)

It should be either "a form input" or "form inputs"

**Comment by hjwp** [comment]
thanks very much for this one too!  how are you enjoying the book?  these chapters are quite freshly rewritten so i'm particularly interested...
