### ISSUE TITLE
为什么代码和书写的一样，还是报错~~没法通过，试了一晚了，急求助

### ISSUE THREAD

**Issue by zhuqunli** [hjwp/Book-TDD-Web-Dev-Python#38]
![snip20160925_2](https://cloud.githubusercontent.com/assets/20615238/18811624/f58a069e-82e8-11e6-9c41-83486ae03f0f.png)

**Comment by hjwp** [comment]
Hi there, can I ask you to send me an email about this issue?  Github isn't the right place for this I think.

I'll need
- a copy/paste of the text from your console
- the contents of tests.py and views.py

thanks!
