### ISSUE TITLE
Number/URL inconsistencies with chapters 13 & 14

### ISSUE THREAD

**Issue by JonathanWillitts** [hjwp/Book-TDD-Web-Dev-Python#39]
Fantastic book so far (thank you!), though just wanted to point out a minor inconsistency with the chapter title and URL numbering that I've just discovered. 

The left hand navigational menu item on the obeythetestinggoat.com site for '13. Dipping Our Toes, Very Tentatively, into JavaScript' points to http://www.obeythetestinggoat.com/book/chapter_14.html, whilst '14. Deploying Our New Code' points to: http://www.obeythetestinggoat.com/book/chapter_13.html.

The same behaviour can be seen on the TOC page too (http://www.obeythetestinggoat.com/pages/book.html#toc).

Nothing too serious, tough though you might like to know!

**Comment by hjwp** [comment]
Fixed! thanks.
