### ISSUE TITLE
Wrong link in chapter 6.2

### ISSUE THREAD

**Issue by FlowFX** [hjwp/Book-TDD-Web-Dev-Python#56]
In [chapter 6.2](http://www.obeythetestinggoat.com/book/chapter_explicit_waits_1.html), in the line

> **Later on**, we’ll refactor out a general wait_for

the **later on** links to chapter 6.2, but is should link to [chapter 11.2](http://www.obeythetestinggoat.com/book/chapter_organising_test_files.html#_a_new_functional_test_tool_a_generic_explicit_wait_helper)

**Comment by hjwp** [comment]
hm.  it works in the pdf but not in the online version.  will dig into it...

**Comment by hjwp** [comment]
fixed this one too!  thx :100:
