### ISSUE TITLE
Wrong link in chapter 4.4

### ISSUE THREAD

**Issue by FlowFX** [hjwp/Book-TDD-Web-Dev-Python#62]
Another broken link for you, on http://www.obeythetestinggoat.com/book/chapter_philosophy_and_refactoring.html#_on_refactoring

`But, as Kent Beck puts it in Test-Driven Development: By Example, ` links to http://www.obeythetestinggoat.com/book/chapter_philosophy_and_refactoring.html#tddbe.

**Comment by hjwp** [comment]
fixed! thanks again!
