### ISSUE TITLE
Link error in chapter 5.5.

### ISSUE THREAD

**Issue by FlowFX** [hjwp/Book-TDD-Web-Dev-Python#63]
Chapter http://www.obeythetestinggoat.com/book/chapter_post_and_database.html#_the_django_orm_and_our_first_model:
![screen shot 2017-03-31 at 17 25 22](https://cloud.githubusercontent.com/assets/800345/24572604/3385ea12-1637-11e7-92c9-bf8946f1ecac.png)

`later on` links to http://www.obeythetestinggoat.com/book/chapter_post_and_database.html#rewrite-model-test which returns to the top of the current page.

`[chapter advanced forms]` should display a different string, shouldn't it?

**Comment by FlowFX** [comment]
Should I continue posting these errors? Or are you aware of them?

**Comment by hjwp** [comment]
Thanks for these.  They're an artefact of the way I built the HTML version -- basically asciidoctor doesn't support multi-page documents, so the book is actually rendered as if it was a single page, and the x-refs are all broken as a result.  I've figured out a way to fix the chapter heading links manually, but I haven't yet written code to fix links to arbitrary points within chapters.

**Comment by hjwp** [comment]
it's here, if you're curious: https://github.com/hjwp/Book-TDD-Web-Dev-Python/blob/master/copy_html_to_site_and_print_toc.py#L75

**Comment by hjwp** [comment]
so i guess the answer is, yes i'm aware of the issue, so it's probably not worth posting any more.  thanks very much for the work so far though, it's much appreciated!

**Comment by hjwp** [comment]
fixed it i think!  https://github.com/hjwp/Book-TDD-Web-Dev-Python/commit/6d4d218005ec4e89b63fffe85f7909d5969f4164 will push out an update soon

**Comment by FlowFX** [comment]
You're welcome.
