### ISSUE TITLE
In prerequisites and assumptions, there's an incomplete sentence

### ISSUE THREAD

**Issue by LeBodro** [hjwp/Book-TDD-Web-Dev-Python#65]
[Right there](https://github.com/hjwp/Book-TDD-Web-Dev-Python/blob/master/pre-requisite-installations.asciidoc#required-software-installations), just under _*The Git version control system*_, some words ceased to exist. There were not erased, only never pushed.

> This is available for any platform, at http://git-scm.com/. On Windows, this comes with the

**Comment by hjwp** [comment]
fixed https://github.com/hjwp/Book-TDD-Web-Dev-Python/commit/8af5eb38c4eb7e1953a8b26bffbc5e791233eaac  thanks!
