### ISSUE TITLE
Chapter 2 functional_tests.py doesn't close Firefox Browser

### ISSUE THREAD

**Issue by bosatsu** [hjwp/Book-TDD-Web-Dev-Python#75]
In Chapter 2. Extending Our Functional Test Using the unittest Module the functional_tests.py looks like the following:

```
from selenium import webdriver
import unittest

class NewVisitorTest(unittest.TestCase):  1

    def setUp(self):  3
        self.browser = webdriver.Firefox()

    def tearDown(self):  3
        self.browser.quit()

    def test_can_start_a_list_and_retrieve_it_later(self):  2
        # Edith has heard about a cool new online to-do app. She goes
        # to check out its homepage
        self.browser.get('http://localhost:8000')

        # She notices the page title and header mention to-do lists
        self.assertIn('To-Do', self.browser.title)  4
        self.fail('Finish the test!')  5

        # She is invited to enter a to-do item straight away
        [...rest of comments as before]

if __name__ == '__main__':  6
    unittest.main(warnings='ignore')  7
```

I found that `self.browser.quit()` does not close firefox, and instead had to use `self.browser.close()`

Reading the documentation for selenium, it seems like this is not expected and quit() should have worked.

I am using MacOS Sierra, python3.6, selenium 3.5.0,  geckodriver 0.18.0, FF 52.1.0 (64-bit)

**Comment by hjwp** [comment]
thanks!  i'm still on geckodriver 17 and selenium 3.4, will look into it.

in the meantime, can you upgrade your firefox?  it looks like geckodriver 18 requires firefox 53 or higher: https://github.com/mozilla/geckodriver/releases

**Comment by hjwp** [comment]
have now tested with selenium 3.5.0, geckodriver 0.18.0 and firefox 54.0 and it works ok for me, which makes me suspect it's your firefox version that needs to be upgraded?  let me know if that works?

**Comment by bosatsu** [comment]
Yes now that I have upgraded to Mozilla 55.01 it works.  Sorry I thought I had upgraded to the latest version of firefox before posting, but after you pointed out the version, I realized it didn't take.   Thank you for prompt replies.

**Comment by hjwp** [comment]
phew, glad it works now.  please don't hesitate to get in touch if you spot anything else you think might be broken!
