### ISSUE TITLE
Link to Deadsnakes PPA is broken

### ISSUE THREAD

**Issue by arnieelkins** [hjwp/Book-TDD-Web-Dev-Python#86]
First, the Deasnakes PPA is actually the Deadsnakes PPA, and second, the current link is not working:

https://launchpad.net/~fkrull/+archive/ubuntu/deadsnakes

That link gives me an error.  I was able to go here:

https://launchpad.net/~deadsnakes

But I am uncertain whether that is the intended destination.

**Comment by asottile** [comment]
maintainer here, here's the new ppa url: https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa

We recently changed names to enable collaboration :)
