### ISSUE TITLE
Chapter 10: nginx unable to see gunicorn socket

### ISSUE THREAD

**Issue by sudoursa** [hjwp/Book-TDD-Web-Dev-Python#93]
For this section of the book:

##############################################################################
Switching to Using Unix Sockets
When we want to serve both staging and live, we can’t have both servers trying to use port 8000. We could decide to allocate different ports, but that’s a bit arbitrary, and it would be dangerously easy to get it wrong and start the staging server on the live port, or vice versa.

A better solution is to use Unix domain sockets—​they’re like files on disk, but can be used by Nginx and Gunicorn to talk to each other. We’ll put our sockets in /tmp. Let’s change the proxy settings in Nginx:

server: /etc/nginx/sites-available/superlists-staging.ottg.eu
server {
    listen 80;
    server_name superlists-staging.ottg.eu;

    location /static {
        alias /home/elspeth/sites/superlists-staging.ottg.eu/static;
    }

    location / {
        proxy_pass http://unix:/tmp/superlists-staging.ottg.eu.socket;
    }
}
Now we restart Gunicorn, but this time telling it to listen on a socket instead of on the default port:

elspeth@server:$ sudo systemctl reload nginx
elspeth@server:$ ./virtualenv/bin/gunicorn --bind \
    unix:/tmp/superlists-staging.ottg.eu.socket superlists.wsgi:application
And again, we rerun the functional test again, to make sure things still pass:

$ STAGING_SERVER=superlists-staging.ottg.eu python manage.py test functional_tests
[...]
OK
Hooray, a change that went without a hitch for once! Moving on.
##############################################################################

I was not so lucky. I was able to create the socket without issue, but the pages wouldn't load. I was seeing the following error logs in nginx:

2018/05/11 16:02:12 [crit] 8944#0: *1 connect() to unix:/tmp/superlists-staging.somesite.com.socket failed (2: No such file or directory) while connecting to upstream, client: 111.111.111.111, se
rver: superlists-staging.somesite.com.socket, request: "GET /favicon.ico HTTP/1.1", upstream: "http://unix:/tmp/superlists-staging.somesite.com.socket:/favicon.ico", host: "superlists-staging.somesite.com", referrer: "http://superlists-staging.somesite.com/"

"No such file or directory" - indicated that nginx couldn't see the socket even though the socket was definitely there:

[nginxuser@otg-staging-server ~]$ ls /tmp/
superlists-staging.somesite.com.socket  
systemd-private-xxxxxxxxxxxxxxx-chronyd.service-z1HGQH  
systemd-private-xxxxxxxxxxxxxxx-nginx.service-SCaqlr

I found the following on the fedora wiki:
http://fedoraproject.org/wiki/Features/ServicesPrivateTmp

This meant that every service sees a completely different /tmp and can only see its own files in that directory, so nginx was unable to see the gunicorn /tmp files.

To fix it I created a directory called /var/sockets with appropriate permissions and replaced the unix:/tmp/ with unix:/var/sockets/ in both the nginx config file and the gunicorn bind command.

The errors went away and I was able to browse to the website using the new socket configuration. 

This is an issue that is probably limited to CentOS 7. (P.S. I had to create a custom policy for selinux as well using the output from "sudo grep nginx /var/log/audit/audit.log | audit2allow -m nginx" following the instructions found here: http://nts.strzibny.name/allowing-nginx-to-use-a-pumaunicorn-unix-socket-with-selinux/)

**Comment by hjwp** [comment]
thanks for letting me know!  have added a footnote in the book.  let me know if you run into anything else in the second half of the book!  and do add a review on amazon if you haven't already!
