### ISSUE TITLE
Chapter 16: Incorrect path to base.html

### ISSUE THREAD

**Issue by ScottMcCormack** [hjwp/Book-TDD-Web-Dev-Python#94]
While running through this chapter I noticed a small issue that I thought I would flag with the path reference towards the end of the chapter: 

https://github.com/hjwp/Book-TDD-Web-Dev-Python/blame/master/chapter_javascript.asciidoc#L737-L738

I believe these should be:
```javascript
<script src="../static/jquery-3.3.1.min.js"></script>
<script src="../static/list.js"></script>
```

**Comment by hjwp** [comment]
I think both would work.  the `/static` versions work using django's static-url generation...
