### ISSUE TITLE
Chapter 1: Python 3.7 and Django - "SyntaxError: Generator expression must be..."

### ISSUE THREAD

**Issue by zecafig** [hjwp/Book-TDD-Web-Dev-Python#99]
If you have updated Python to 3.7 version, you will get the following error when trying to do the `python3 manage.py runserver` command.

"SyntaxError: Generator expression must be parenthesized"

**Comment by zecafig** [comment]
To fix this, edit this file: [virtual env directory]/lib/python3.7/site-packages/django/contrib/admin/widgets.py

delete the following lines [150-153] 

```
        related_url += '?' + '&amp;'.join(
                    '%s=%s' % (k, v) for k, v in params.items(),
                )
```
and add this in place:

`related_url += '?' + '&amp;'.join('%s=%s' % (k, v) for k, v in params.items())`

ref: https://github.com/django/django/commit/931c60c5216bd71bc11f489e00e063331cf21f40

**Comment by emmanuelmhetupython** [comment]
Thanks, l also have that problem and was solved with your suggestion. l hope that there are no more problems using python3.7 and django in virtualenv

**Comment by hjwp** [comment]
I thought the latest point release of django 1.11 actually fixed this anyway?

**Comment by addohm** [comment]
> I thought the latest point release of django 1.11 actually fixed this anyway?

It's still an issue.

**Comment by hjwp** [comment]
I can't reproduce this:

```
👉  cd /tmp              
👉  python3 -m venv .venv
👉  source .venv/bin/activate
👉  python --version          
Python 3.7.3
👉  pip install 'django<2'        
Collecting django<2
  Downloading https://files.pythonhosted.org/packages/61/cb
[...]
Successfully installed django-1.11.23 pytz-2019.2
👉  which django-admin
/tmp/.venv/bin/django-admin
👉  django-admin startproject myproject                       
👉  cd myproject 
👉  ls
manage.py  myproject
👉  python manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).

You have 13 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.

August 15, 2019 - 13:06:00
Django version 1.11.23, using settings 'myproject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
^C%                                                                                                                  
```

?

**Comment by hjwp** [comment]
from https://docs.djangoproject.com/id/2.1/releases/1.11.17/

> Django 1.11.17 fixes several bugs in 1.11.16 and adds compatibility with Python 3.7.

**Comment by charolynmendoza** [comment]
Fixed by installing a recent version of Django instead. https://www.djangoproject.com/download/

**Comment by garry5296** [comment]
i m not able to reach that location on the machine can u please help out [virtual env directory]/lib/python3.7/site-packages/django/contrib/admin/widgets.py. 
![github_help](https://user-images.githubusercontent.com/55591744/101981881-0e714f80-3c96-11eb-852a-75c57303942c.PNG)

**Comment by hjwp** [comment]
just to re-iterate:  i recommend you use the latest version of django `1.11` that exists, and as far as i know it is compatible with python 3.7.  if you upgrade to django 3 you will have to spend time figuring out which problems are real problems and which are just due to django version differences.

**Comment by mahbubu1640** [comment]
thank you very much
where can I talk to you 
can you share me your any social media account
